# Generated by Django 3.0.6 on 2020-07-09 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter The Name', max_length=100)),
                ('phone', models.CharField(help_text='Enter the phone number', max_length=100)),
                ('bday', models.DateField(verbose_name='Birthday')),
                ('mail', models.EmailField(help_text='Enter the e-mail', max_length=254)),
                ('blackboard', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
