# Generated by Django 3.0.6 on 2020-07-09 09:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='blackboard',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
